// This code was generated by yarn icons. Changes will be lost if the code is regenerated.
import * as React from "react"

import * as types from "../types"

export class AirplaneIcon extends React.PureComponent<types.IconProps> {
  render() {
    const props = this.props
    return (
      <svg viewBox="0 0 26 24" width="24" height="24" {...props}>
        <g fill="inherit" fillRule="nonzero">
          <path d="M24.82 5.936l-20.784 12-2-3.464 20.785-12a2 2 0 1 1 2 3.464z" />
          <path d="M6 13.338l-3.464 2-2.5-4.33.866-.5zM17.259 6.838l-6.063 3.5-8.098-8.026 1.732-1zM7 15.07l-3.464 2 2.5 4.33.866-.5zM18.259 8.57l-6.063 3.5 2.902 11.026 1.732-1z" />
        </g>
      </svg>
    )
  }
}
