// This code was generated by yarn icons. Changes will be lost if the code is regenerated.
import * as React from "react"

import * as types from "../types"

export class AttachmentIcon extends React.PureComponent<types.IconProps> {
  render() {
    const props = this.props
    return (
      <svg viewBox="0 0 24 22" width="24" height="24" {...props}>
        <path
          d="M16.431 5.982L7.72 14.75a.74.74 0 0 1-1.045 0 .745.745 0 0 1 0-1.05l10.21-10.276a1.075 1.075 0 0 1 1.533 0l2.3 2.315a1.097 1.097 0 0 1 0 1.544l-10.21 10.275a4.667 4.667 0 0 1-6.621 0 4.738 4.738 0 0 1 0-6.666l8.712-8.767a1.241 1.241 0 0 0 0-1.752 1.229 1.229 0 0 0-1.742 0L2.144 9.139c-2.789 2.808-2.789 7.363 0 10.17a7.115 7.115 0 0 0 10.105 0L23.227 8.263a2.496 2.496 0 0 0 0-3.51L19.393.9a2.449 2.449 0 0 0-3.485 0L4.931 11.947a3.236 3.236 0 0 0 0 4.555 3.188 3.188 0 0 0 4.53 0l8.713-8.767a1.241 1.241 0 0 0 0-1.753 1.23 1.23 0 0 0-1.743 0z"
          fill="inherit"
          fillRule="evenodd"
        />
      </svg>
    )
  }
}
