// This code was generated by yarn icons. Changes will be lost if the code is regenerated.
import * as React from "react"

import * as types from "../types"

export class CoffeeIcon extends React.PureComponent<types.IconProps> {
  render() {
    const props = this.props
    return (
      <svg viewBox="0 0 24 24" width="24" height="24" {...props}>
        <path
          d="M21.517 7.966c0-.69-.241-1.276-.724-1.76a2.394 2.394 0 0 0-1.759-.723h-.827v4.965h.827c.69 0 1.276-.241 1.76-.724a2.394 2.394 0 0 0 .723-1.758zM0 17.896h23.172a3.19 3.19 0 0 1-.97 2.341 3.19 3.19 0 0 1-2.34.97H3.31a3.19 3.19 0 0 1-2.34-.97 3.19 3.19 0 0 1-.97-2.34zm24-9.93c0 1.37-.485 2.54-1.455 3.51-.97.97-2.14 1.455-3.51 1.455h-.828v.414c0 .793-.285 1.474-.854 2.043a2.788 2.788 0 0 1-2.043.853H6.207a2.788 2.788 0 0 1-2.043-.853 2.788 2.788 0 0 1-.854-2.043V3.828c0-.225.082-.419.246-.582A.795.795 0 0 1 4.138 3h14.896c1.371 0 2.541.485 3.511 1.455.97.97 1.455 2.14 1.455 3.51z"
          fill="inherit"
          fillRule="nonzero"
        />
      </svg>
    )
  }
}
