// This code was generated by yarn icons. Changes will be lost if the code is regenerated.
import * as React from "react"

import * as types from "../types"

export class FacebookIcon extends React.PureComponent<types.IconProps> {
  render() {
    const props = this.props
    return (
      <svg viewBox="0 0 24 24" width="24" height="24" {...props}>
        <path
          d="M8.481 24h4.967V11.999h3.313l.439-4.136h-3.752l.005-2.07c0-1.078.103-1.657 1.653-1.657h2.07V0h-3.314c-3.98 0-5.38 2.007-5.38 5.38v2.483H6V12h2.481V24z"
          fill="inherit"
          fillRule="nonzero"
        />
      </svg>
    )
  }
}
