// This code was generated by yarn icons. Changes will be lost if the code is regenerated.
import * as React from "react"

import * as types from "../types"

export class LocationIcon extends React.PureComponent<types.IconProps> {
  render() {
    const props = this.props
    return (
      <svg viewBox="0 0 24 24" width="24" height="24" {...props}>
        <path
          d="M12 24s9-8.373 9-15c0-6.627-4.029-9-9-9S3 2.373 3 9s9 15 9 15zM7.5 7.5a4.5 4.5 0 1 1 9 0 4.5 4.5 0 0 1-9 0z"
          fill="inherit"
          fillRule="nonzero"
        />
      </svg>
    )
  }
}
