module.exports = (code, config, state) => {
  return (
    `// This code was generated by yarn icons. Changes will be lost if the code is regenerated.\n` +
    `import * as React from "react"\n\n` +
    `import * as types from "../types"\n\n` +
    `export class ${state.componentName.replace(
      "Svg",
      ""
    )} extends React.PureComponent<types.IconProps> {\n` +
    `render () {\n` +
    `const props = this.props\n` +
    `return ${code}\n` +
    `}\n` +
    `}\n`
  )
}
